from snakemake.utils import min_version
min_version("6.0.0")

configfile: "config/config.yaml"

report: "report/workflow.rst"

include: "rules/common.smk"
include: "rules/annotation.smk"
include: "rules/strling.smk"
include: "rules/table.smk"
include: "rules/utils.smk"
include: "rules/ref.smk"

# targets = []
# for group in groups_no_control:
#     targets.extend(expand("results/strling/vcf/{group}/{group}.all.annotated.bcf", group=[group]))


rule all:
    input:
        "results/strling/tables/TOC-SAL-DAV/TOC-SAL-DAV.tsv",
        "results/strling/vcf/TOC-SAL-DAV/TOC-SAL-DAV.all.annotated.filtered.bcf"
        # "results/strling/vcf/TOC-SAL-DAV/TOC-SAL-DAV.all.annotated.bcf"
        #expand("results/strling/plots/{group}.pdf", group="TOC-SAL-DAV"), #group=groups_no_control
        #expand("results/strling/tables/{group}/{group}.xlsx", group=groups_no_control)


rule only_bai_linking:
    input:
        expand("{x}.bai", x=samples["bam"])
