samples: config/samples.tsv


ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 25
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 100
  # Genome build
  build: GRCh38
  # Ensembl release to use for SnpEff annotation (sometimes, the latest Ensembl release is not available in SnpEff)
  snpeff_release: 86

annotations:
  vep:
    params: ""
    plugins: ""
      # Add any plugin from https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
      # Plugin args can be passed as well, e.g. "LoFtool,path/to/custom/scores.txt".
      #- LoFtool
  genehancer:
    # ONLY ACTIVATE IF YOU HAVE EXPLICIT PERMISSION TO USE GENEHANCER
    activate: true

experiments:
  fame:
    case:
      - fame
    control:
      - ilaria
      - control
      - TOC-SAL-DAV
      - E21-0561
      - tremor
      - 62672645_s6
      - bur
      - dan
      - ataxia
      - aicardi_1480
      - aicardi_1875
      - aicardi_2125
      - aicardi_2410
      - E20-0566
      - E18-0675
      - E21-0052
      - PED-SAL-BOU
      - LOU
  E21-0561:
    case:
      - E21-0561
    control:
      - ilaria
      - control
      - TOC-SAL-DAV
      - fame
      - tremor
      - 62672645_s6
      - bur
      - dan
      - ataxia
      - aicardi_1480
      - aicardi_1875
      - aicardi_2125
      - aicardi_2410
      - E20-0566
      - E18-0675
      - E21-0052
      - PED-SAL-BOU
      - LOU
  E20-0566:
    case:
      - E20-0566
    control:
      - ilaria
      - control
      - TOC-SAL-DAV
      - fame
      - tremor
      - 62672645_s6
      - bur
      - dan
      - ataxia
      - aicardi_1480
      - aicardi_1875
      - aicardi_2125
      - aicardi_2410
      - E21-0561
      - E18-0675
      - E21-0052
      - PED-SAL-BOU
      - LOU
  E18-0675:
    case:
      - E18-0675
    control:
      - ilaria
      - control
      - TOC-SAL-DAV
      - fame
      - tremor
      - 62672645_s6
      - bur
      - dan
      - ataxia
      - aicardi_1480
      - aicardi_1875
      - aicardi_2125
      - aicardi_2410
      - E21-0561
      - E20-0566
      - E21-0052
      - PED-SAL-BOU
      - LOU
  E21-0052:
    case:
      - E21-0052
    control:
      - ilaria
      - control
      - TOC-SAL-DAV
      - fame
      - tremor
      - 62672645_s6
      - bur
      - dan
      - ataxia
      - aicardi_1480
      - aicardi_1875
      - aicardi_2125
      - aicardi_2410
      - E21-0561
      - E20-0566
      - E18-0675
      - PED-SAL-BOU
      - LOU
  PED-SAL-BOU:
    case:
      - PED-SAL-BOU
    control:
      - ilaria
      - control
      - TOC-SAL-DAV
      - fame
      - tremor
      - 62672645_s6
      - bur
      - dan
      - ataxia
      - aicardi_1480
      - aicardi_1875
      - aicardi_2125
      - aicardi_2410
      - E21-0561
      - E20-0566
      - E18-0675
      - E21-0052
      - LOU
  LOU:
    case:
      - LOU
    control:
      - ilaria
      - control
      - TOC-SAL-DAV
      - fame
      - tremor
      - 62672645_s6
      - bur
      - dan
      - ataxia
      - aicardi_1480
      - aicardi_1875
      - aicardi_2125
      - aicardi_2410
      - E21-0561
      - E20-0566
      - E18-0675
      - E21-0052
      - PED-SAL-BOU
  genome15:
    case:
      - E21-0561
      - E20-0566
      - E18-0675
      - E21-0052
      - PED-SAL-BOU
      - LOU
    control:
      - ilaria
      - control
      - TOC-SAL-DAV
      - fame
      - tremor
      - 62672645_s6
      - bur
      - dan
      - ataxia
      - aicardi_1480
      - aicardi_1875
      - aicardi_2125
      - aicardi_2410